config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'dashboard/index', as: 'dashboard'
  get 'dashboard/profile'

  post 'projects/join', as: 'join_project'
  resources :projects do
    get 'view'
    resources :members
    resources :stories do
      resources :story_files
      resources :tasks do
        post 'state'
      end
      post 'state'
      get 'assigned_members'
      post 'assign_member'
      delete 'unassign_member'
    end
  end

   root 'welcome#index', as: 'welcome'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :story
  validates :name , presence: true
  validates_uniqueness_of :name, scope: :story_id
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: [:edit,:update]
	#before_action :verify_user_assinged_to_story_or_is_project_creator!
	before_action :set_project!
	def index
		@story = @project.stories.find(params[:story_id])
		@tasks = @story.tasks.paginate(:page => params[:page], :per_page => 10)
	end
	def new
		if @project
			@story = @project.stories.find(params[:story_id])
			if @story
				@task = @story.tasks.new
			end
		else
		end
	end
	def edit

	end
	def update
		respond_to do |format|
			if @task.update(task_params)
				format.html
				format.js
			else
				format.html
				format.js
			end
		end
	end
	def create
		@story = @project.stories.find(params[:story_id])
		if !params[:render_normal].nil?
			@render_default = false
		else
			@render_default = true
		end
		if @story
			@task = @story.tasks.new(task_params)
			respond_to do |format|
				if @task.save
					format.html
					format.js
				else
					format.html
					format.js
				end
			end
		end
	end

	def state
		@story = @project.stories.find(params[:story_id])
		@task = @story.tasks.find(params[:task_id])
		@task.update(:state=>params[:state])
	end
	private

	def set_task
		@task = @project.stories.find(params[:story_id]).tasks.find(params[:id])
	end

	def task_params
		params.require(:task).permit(:name,:description)
	end
	def verify_user_assinged_to_story_or_is_project_creator!
		project = current_user.projects.where("id = ?",params[:project_id])
		if project.count == 0
			project = Project.find(params[:project_id])
			if project
				story = project.stories.find(params[:story_id])
				project_member = project.project_members.find_by(:user_id => current_user)
				if story.member_stories.find_by(:project_member_id => project_member.id) == nil
					redirect_to project_stories_url(project)
				else
					@assigned_user = true
				end
			end
		end
	end
	
end

app/helpers/tasks_helper.rb
module TasksHelper
	def task_errors!
		if @task.errors.any?
			sentence = I18n.t('errors.messages.not_saved',
				      count: @task.errors.count,
				      resource: @task.class.model_name.human.downcase)
			content_tag(:div,:class => "alert alert-danger") do
				concat content_tag(:button, "x", :type =>"button", :class =>"close", "data-dismiss" => "alert")
				concat content_tag(:h4,sentence) 
				concat content_tag(:ul,@task.errors.full_messages.map { |msg| content_tag(:li, msg) }.join('').html_safe)
			end
		end
	end
	def tasks!
		counter = 0;
		content_tag(:table,:class=>"table") do
			 content_tag(:thead,content_tag(:tr,content_tag(:th,"#")+content_tag(:th,"Name")+content_tag(:th,"Description")+content_tag(:th,"Action")))+
		     content_tag(:tbody) do
				@story.tasks.each do |task|
					concat content_tag(:tr,content_tag(:th,counter= counter+1,:scope=>"row")+content_tag(:td,task.name).html_safe+content_tag(:td,task.description).html_safe)
				end
			end
		end
	end
	def task_success!
		content_tag(:div,:class => "alert alert-success") do
			concat content_tag(:button, "x", :type =>"button", :class =>"close", "data-dismiss" => "alert")
			concat content_tag(:h4,"Story has been updated.") 
		end
	end
end

app/views/tasks/_form.html.haml
%div{:class => "col-lg-3"}
%div{:class => "col-lg-6"}
  %h1
    #{@task.story.name}
    %small
      Task
  = form_for([@task.story.project, @task.story, @task],  html: {remote:true }) do |f|
    .form-group
      = f.label :name
      %br
      = f.text_field :name, :class=> "form-control"
    .form-group
      = f.label :description
      %br
      = f.text_area :description, :class => 'form-control'

    = f.submit :value => "Save", :class => 'btn btn-success'
  %br
  .row
    #table
%div{:class => "col-lg-3"}

app/views/tasks/create.js.haml
- if @render_default == false
  $('.content').html('#{story_details!}');
-else
  $('#success').html('');
  $('#errors').html('');
  - if @task.errors.any?
    $('#errors').html('#{task_errors!}');
  - else
    $('form').find("input[type=text], textarea").val("");
    $('#table').html('#{tasks!}');

app/views/tasks/edit.html.haml
= render 'form'

app/views/tasks/index.html.haml
%h1
  = @story.name
  %small
    Tasks
    = link_to "Add Task",new_project_story_task_url(:project_id=>@story.project.id, :story_id => @story.id),remote: true, class:"btn btn-success pull-right"
%br/
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        Title
      %th
        Description
      %th
        Actions
  %tfoot
    %tr
      %td{colspan:"3"}
        %center
          = will_paginate @tasks
  %tbody
    - @tasks.each do |task|
      %tr
        %td
          = task.name
        %td
          = task.description
        %td
          = link_to "Edit", edit_project_story_task_url(@story.project_id, @story, task)

app/views/tasks/new.js.haml
- if @task
  $('#main').html("#{escape_javascript(render 'form')}");

app/views/tasks/state.js.haml
$('.content').html('#{story_details!}');

app/views/tasks/update.js.haml
$('#success').html('');
$('#errors').html('');
- if @task.errors.any?
  $('#errors').html('#{task_errors!}');
- else
  $('#success').html('#{task_success!}');