config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'dashboard/index', as: 'dashboard'
  get 'dashboard/profile'

  post 'projects/join', as: 'join_project'
  resources :projects do
    get 'view'
    resources :members
    resources :stories do
      resources :story_files
      resources :tasks do
        post 'state'
      end
      post 'state'
      get 'assigned_members'
      post 'assign_member'
      delete 'unassign_member'
    end
  end

   root 'welcome#index', as: 'welcome'

end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :password, length: { minimum: 6 }
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ActionController::Base.helpers.asset_path("pf-default.jpeg")
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/gif", "image/png"] }

  has_many :projects
  has_many :project_members
  has_many :projects_joined, :class_name => "Project", :foreign_key => "project_id" ,through: :project_members , source: :project
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.html.haml
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/shared/_nav_bar_links.haml
- if controller_name != 'sessions' and current_user == nil
  %li
    = link_to "Log in", new_session_path(resource_name) 
  %br
- if current_user == nil and devise_mapping.registerable? && controller_name != 'registrations'
  %li
    = link_to "Sign up", new_registration_path(resource_name) 
  %br
- if user_signed_in?
  %li
    = link_to "Create Project", new_project_url
  %li
    .row{style: "text-align:center;vertical-align:middle;height:100%;"}
      .col-md-2
        = image_tag current_user.avatar.url,width:"24", height: "24", alt: "#{current_user.first_name.chars.first}#{current_user.last_name.chars.first}"
      .col-md-8
        = link_to "#{current_user.first_name} #{current_user.last_name}", dashboard_profile_url
  %li
    = link_to "Sign out", destroy_user_session_url, method: :delete