config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'dashboard/index', as: 'dashboard'
  get 'dashboard/profile'

  post 'projects/join', as: 'join_project'
  resources :projects do
    get 'view'
    resources :members
    resources :stories do
      resources :story_files
      resources :tasks do
        post 'state'
      end
      post 'state'
      get 'assigned_members'
      post 'assign_member'
      delete 'unassign_member'
    end
  end

   root 'welcome#index', as: 'welcome'

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :stories
	has_many :project_members
	has_many :users, through: :project_members
	validates :title, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:edit, :update]
	before_action :has_project_access!, only: [:view]
	before_action :set_project!, only: [:view]
	def index
		@projects = current_user.projects.paginate(:page => params[:page], :per_page => 10)
		@other_projects = current_user.project_members
	end

	def show

  	end

	def new
		@project = current_user.projects.new
	end

	def create
		@project = current_user.projects.new(project_params)
		@users = User.where("id != ? " ,current_user.id)
		respond_to do |format|
			if @project.save
				format.html{ redirect_to welcome_index}
				format.js
			else
				format.html{render new_project_path}
				format.js
			end
		end
	end
	def edit
		
	end
	def update
		respond_to do |format|
			if @project.update(project_params)
				format.html{ redirect_to welcome_index}
				format.js
			else
				format.html{render new_project_path}
				format.js
			end
		end
	end
	def join
		
	end
	def view
	
	end

	private
	def set_project
		@project = current_user.projects.find(params[:id])
	end
	def project_params
		params.require(:project).permit(:title,:description)
	end
	def has_project_access!
		begin
			current_user.projects.find(params[:project_id])
		rescue
			project = Project.find(params[:project_id]).project_members.where('user_id = ?' ,current_user.id)
			if project.count == 0
				redirect_to projects_url
			end
		end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def project_errors!
		if @project.errors.any?
			sentence = I18n.t('errors.messages.not_saved',
				      count: @project.errors.count,
				      resource: @project.class.model_name.human.downcase)
			content_tag(:div,:class => "alert alert-danger") do
				concat content_tag(:button, "x", :type =>"button", :class =>"close", "data-dismiss" => "alert")
				concat content_tag(:h4,sentence) 
				concat content_tag(:ul,@project.errors.full_messages.map { |msg| content_tag(:li, msg) }.join('').html_safe)
			end
		end
	end
	def project_success!
		content_tag(:div,:class => "alert alert-success") do
			concat content_tag(:button, "x", :type =>"button", :class =>"close", "data-dismiss" => "alert")
			concat content_tag(:h4,"Project has been updated.") 
			#concat content_tag(:ul,@project.errors.full_messages.map { |msg| content_tag(:li, msg) }.join('').html_safe)
		end
	end
end

app/views/projects/_form.html.haml
= form_for @project, remote:true do |f|
  .form-group
    = f.label :title
    %br
    = f.text_field :title, :class=> "form-control"
  .form-group
    = f.label :description
    %br
    = f.text_area :description, :class => 'form-control'

  = f.submit :value => "Save", :class => 'btn btn-success'
%br

app/views/projects/_members.html.haml
%h1
  #{@project.title}
  %small
    Select members
    = link_to 'Add Story', new_project_story_url(:project_id => @project.id),:class => "btn btn-success pull-right", role: "button", remote: :true


%br/
- @users.each do |user|
  %div{class: ".col-sm-3 col-md-3", id: "user_#{user.id}"}
    .thumbnail
      = image_tag user.avatar.url, wdith: "100%"
      .caption
        %h3
          = "#{user.first_name} #{user.last_name}"
          %br
          %small
            = "#{user.email}"
        %p
          = link_to 'Add', project_members_url(:project_id => @project.id,:user_id => user.id),:class => "btn btn-primary", role: "button", :style=>"width:100%", remote: :true, method: :post

app/views/projects/_other_projects.html.haml
%h1
  Joined
  %small
    Projects
%br/
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        Title
      %th
        Description
      %th
        Actions
  %tbody
    - @other_projects.each do |member|
      %tr
        %td
          = link_to "#{member.project.title}", project_view_url(member.project)
        %td
          = member.project.description
        %td
          = link_to "Stories", project_stories_url(member.project)
          |
          = link_to "Members", project_members_url(member.project)

app/views/projects/_projects.html.haml
%h1
  My
  %small
    Projects
%br/
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        Title
      %th
        Description
      %th
        Actions
  %tfoot
    %tr
      %td{colspan:"3"}
        %center
          = will_paginate @projects
  %tbody
    - @projects.each do |project|
      %tr
        %td
          = link_to "#{project.title}", project_view_url(project)
        %td
          = project.description
        %td
          = link_to "Edit", edit_project_url(project)
          |
          = link_to "Stories", project_stories_url(project)
          |
          = link_to "Members", project_members_url(project)

app/views/projects/create.js.haml
$('#success').html('');
$('#errors').html('');
- if @project.errors.any?
  $('#errors').html('#{project_errors!}');
- else
  $('form').find("input[type=text], textarea").val("");
  $('#main').html("#{escape_javascript(render 'members')}");

app/views/projects/edit.html.haml
%div{:class => "col-lg-3"}
%div{:class => "col-lg-6"}
  %h1
    Edit
    %small
      project
  = render 'form'
%div{:class => "col-lg-3"}

app/views/projects/index.html.haml
= render 'projects/projects'
%br/
= render 'projects/other_projects'

app/views/projects/join.js.haml
- if @project_member.errors.any?
  alert('Error');
- else
  $("#user_#{@user.id}").fadeOut('slow');

app/views/projects/new.html.haml
%div{:class => "col-lg-3"}
%div{:class => "col-lg-6"}
  %h1
    Create
    %small
      project
  = render 'form'
%div{:class => "col-lg-3"}

app/views/projects/update.js.haml
$('#success').html('');
$('#errors').html('');
- if @project.errors.any?
  $('#errors').html('#{project_errors!}');
- else
  $('#success').html('#{project_success!}');
  

app/views/projects/view.html.haml
#project{:value=>"#{@project.id}"}

#open.col-lg-4
  .column
    %h4
      Open
    .docker
      - @project.stories.open.each do |story|
        - if story.member_stories.find_by(:project_member_id => @project.project_members.find_by(:user_id=> current_user.id)) != nil
          .docker-item
            %input{:type=>"hidden", :value=>"#{story.id}"}
            %div.story-title
              %h5
                %small
                = story.id 
                |
                = story.name
            %div
              %p
                = story.description
      %div
#doing.col-lg-4{:style=>"height:900px;"}
  .column
    %h4
      Doing
    .docker
      - @project.stories.doing.each do |story|
        .docker-item
          %input{:type=>"hidden", :value=>"#{story.id}"}
          %div.story-title
            %h5
              %small
              = story.id 
              |
              = story.name
          %div
            %p
              = story.description
      %div
#done.col-lg-4
  .column
    %h4
      Done
    .docker
      - @project.stories.done.each do |story|
        .docker-item
          %input{:type=>"hidden", :value=>"#{story.id}"}
          %div.story-title
            %h5
              %small
              = story.id 
              |
              = story.name
          %div
            %p
              = story.description
      %div


%div{:class=>"modal fade",id:"storyModal",tabindex:"-1", role:"dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button{type:"button",class:"close","data-dismiss"=>"modal","aria-label"=>"Close"}
          %span{"aria-hidden"=>"true"}
            &times;
        %h4.modal-title
          User
      .modal-body
        
        .row
          .col-lg-2
          .col-lg-8
            .form-group
            %input{:type=>"hidden", :placeholder=>"Task name",:class=> "form-control",:id=>"project_id", :value=>""}
              %input{:type=>"hidden", :placeholder=>"Task name",:class=> "form-control",:id=>"story_id", :value=>""}
              %input{:type=>"text", :placeholder=>"Task name",:class=> "form-control",:id=>"task_name"}
            %br/
            .form-group
              %input{:type=>"text",:placeholder=>"Task description", :class=> "form-control",:id=>"task_description"}
            %br/
            %input{:type=>"button",:value=>"Add",:class=>"btn btn-success", :onclick=>"submit_task()"}
          .col-lg-2
        %br/
        %h4
          Tasks
        .content
      .modal-footer
        %button{type:"button",class:"btn btn-default","data-dismiss"=>"modal"}
          Close