config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'dashboard/index', as: 'dashboard'
  get 'dashboard/profile'

  post 'projects/join', as: 'join_project'
  resources :projects do
    get 'view'
    resources :members
    resources :stories do
      resources :story_files
      resources :tasks do
        post 'state'
      end
      post 'state'
      get 'assigned_members'
      post 'assign_member'
      delete 'unassign_member'
    end
  end

   root 'welcome#index', as: 'welcome'

end

app/models/story.rb
class Story < ActiveRecord::Base
  scope :open, -> {where(state:'open')}
  scope :doing, -> {where(state:'doing')}
  scope :done, -> {where(state:'done')}
  belongs_to :project
  has_many :story_files
  has_many :tasks
  has_many :member_stories
  validates :name, presence: true
  validates_uniqueness_of :name, scope: :project_id

  accepts_nested_attributes_for :tasks,
    :allow_destroy => true,
    :reject_if     => :all_blank
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_action :set_project!
	before_action :set_story, only: [:edit,:update]
	

	def index
		@stories = @project.stories.paginate(:page => params[:page], :per_page => 10)
	end
	def new
		@project = current_user.projects.find(params[:project_id])
		if @project
			@story = @project.stories.new
		else
		end
	end
	def assigned_members
		@story = current_user.projects.find(params[:project_id]).stories.find(params[:story_id])
		@members = current_user.projects.find(params[:project_id]).project_members.paginate(:page => params[:page], :per_page => 10)
	end
	def assign_member
		@member = current_user.projects.find(params[:project_id]).stories.find(params[:story_id]).member_stories.new
		@member.project_member_id = params[:user_id]
		if @member.save
			redirect_to project_story_assigned_members_url(params[:project_id],params[:story_id])
		else
			redirect_to project_story_assigned_members_url(params[:project_id],params[:story_id], notice: 'Failed to assing user')
		end
	end
	def unassign_member
		@member = current_user.projects.find(params[:project_id]).stories.find(params[:story_id]).member_stories.find_by(:project_member_id => params[:user_id])
		if @member.destroy
			redirect_to project_story_assigned_members_url(params[:project_id],params[:story_id])
		else
			redirect_to project_story_unassigned_members_url(params[:project_id],params[:story_id], notice: 'Failed to unassing user')
		end
	end
	def show
		@story = @project.stories.find(params[:id])
		respond_to do |format|
			format.html
			format.js
		end
	end
	def edit
	end
	def create
		@project = current_user.projects.find(params[:project_id])
		if @project
			@story = @project.stories.new(story_params)
			respond_to do |format|
				if @story.save
					if params[:files]
						params[:files].each do |file|
							@story.story_files.create(file: file)
						end
					end
					format.html
					format.js
				else
					format.html
					format.js
				end
			end
		end
	end
	def update
		respond_to do |format|
			if @story.update(story_params)
				if params[:files]
					params[:files].each do |file|
						@story.story_files.create(file: file)
					end
				end
				format.html
				format.js
			else
				format.html
				format.js
			end
		end
	end
	def state
		@story = @project.stories.find(params[:story_id])
		@story.update(:state=>params[:state])
	end
	private
	def set_story
		@project = current_user.projects.find(params[:project_id])
		@story = @project.stories.find(params[:id])
	end
	def story_params
		params.require(:story).permit(:name,:description)
	end
end

app/helpers/stories_helper.rb
module StoriesHelper
	def story_errors!
		if @story.errors.any?
			sentence = I18n.t('errors.messages.not_saved',
				      count: @story.errors.count,
				      resource: @story.class.model_name.human.downcase)
			content_tag(:div,:class => "alert alert-danger") do
				concat content_tag(:button, "x", :type =>"button", :class =>"close", "data-dismiss" => "alert")
				concat content_tag(:h4,sentence) 
				concat content_tag(:ul,@story.errors.full_messages.map { |msg| content_tag(:li, msg) }.join('').html_safe)
			end
		end
	end
	def stories!
		counter = 0;
		content_tag(:table,:class=>"table") do
			 content_tag(:thead,content_tag(:tr,content_tag(:th,"#")+content_tag(:th,"Name")+content_tag(:th,"Description")+content_tag(:th,"Action")))+
		     content_tag(:tbody) do
		     	
				@project.stories.each do |story|
					concat content_tag(:tr,content_tag(:th,counter= counter+1,:scope=>"row")+content_tag(:td,story.name).html_safe+content_tag(:td,story.description).html_safe+content_tag(:td,link_to("Add Task",new_project_story_task_url(:project_id=>@project.id, :story_id => @story.id),remote: true)))
				end
			end
		end
	end
	def story_success!
		content_tag(:div,:class => "alert alert-success") do
			concat content_tag(:button, "x", :type =>"button", :class =>"close", "data-dismiss" => "alert")
			concat content_tag(:h4,"Story has been updated.") 
			#concat content_tag(:ul,@project.errors.full_messages.map { |msg| content_tag(:li, msg) }.join('').html_safe)
		end
	end
	
end

app/views/stories/_form.html.haml
%div{:class => "col-lg-3"}
%div{:class => "col-lg-6"}
  %h1
    %small
      Story
     
  = form_for([@project, @story],  html: { multipart: true ,remote:true })   do |f|
    .form-group
      = f.label :name
      %br
      = f.text_field :name, :class=> "form-control"
    .form-group
      = f.label :description
      %br
      = f.text_area :description, :class => 'form-control'
    .form-group
      = f.label 'Documents'
      %br
      = file_field_tag "files[]", type: :file, multiple: true 

    = f.submit :value => "Save", :class => 'btn btn-success'
  %br

  .row
    #table
%div{:class => "col-lg-3"}

app/views/stories/assigned_members.html.haml
%h1
  = @story.name
  %small
    Stories
%br/
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        Avatar
      %th
        Name
      %th
        Actions
  %tfoot
    %tr
      %td{colspan:"3"}
        %center
          = will_paginate @members
  %tbody
    - @members.each do |member|
      %tr
        %td
          = image_tag member.user.avatar.url, width:"100", heght: "100"
          
        %td
          = member.user.first_name
          = member.user.last_name 
        %td
          - if member.member_stories.find_by(story_id: @story) != nil
            = link_to "unassign", project_story_unassign_member_url(@story.project,@story,:user_id => member.id) , method: :delete
          - else
            = link_to "assign", project_story_assign_member_url(@story.project,@story,:user_id => member.id), method: :post

app/views/stories/create.js.haml
$('#success').html('');
$('#errors').html('');
- if @story.errors.any?
  $('#errors').html('#{story_errors!}');
- else
  $("#files_").val('');
  $('form').find("input[type=text], textarea").val("");
  $('#table').html('#{stories!}');

app/views/stories/edit.html.haml
= render 'form'

app/views/stories/index.html.haml
%h1
  = @project.title
  %small
    Stories
    - if @assigned_user
    -else
      = link_to 'Add Story', new_project_story_url(:project_id => @project.id),:class => "btn btn-success pull-right", role: "button", remote: :true
%br/
%table{:class => "table table-hover"}
  %thead
    %tr
      %th
        Title
      %th
        Description
      %th
        Actions
  %tfoot
    %tr
      %td{colspan:"3"}
        %center
          = will_paginate @stories
  %tbody
    - @stories.each do |story|
      - if @assigned_user == true && story.member_stories.find_by(:project_member_id => @project.project_members.find_by(:user_id=> current_user.id)) != nil
        %tr
          %td
            = story.name
          %td
            = story.description
          %td
            = link_to "Tasks", project_story_tasks_url(@project, story)
            |
            = link_to "Documents", project_story_story_files_url(@project,story)
      -else
        - if @project.user.id == current_user.id
          %tr
            %td
              = story.name
            %td
              = story.description
            %td
              = link_to "Edit", edit_project_story_url(@project, story)
              |
              = link_to "Tasks", project_story_tasks_url(@project, story)
              |
              = link_to "Documents", project_story_story_files_url(@project,story)
              |
              = link_to "Assigned Members", project_story_assigned_members_url(@project,story)
      

app/views/stories/new.js.haml
- if @story
  $('#main').html("#{escape_javascript(render 'form')}");

app/views/stories/show.html.haml
= @story.name

app/views/stories/show.js.haml
$('.content').html('#{story_details!}');

app/views/stories/update.js.haml
$('#success').html('');
$('#errors').html('');
- if @story.errors.any?
  $('#errors').html('#{story_errors!}');
- else
  $("#files_").val('');
  $('#success').html('#{story_success!}');